# Generated by Django 2.2.12 on 2020-11-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201011_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='balance',
            field=models.CharField(max_length=50, verbose_name='Баланс филиала'),
        ),
    ]
