# Generated by Django 2.2.12 on 2020-11-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201101_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Баланс филиала'),
        ),
    ]
