# Generated by Django 2.2.12 on 2020-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201101_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_shipping_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней отгрузки'),
        ),
        migrations.AddField(
            model_name='branch',
            name='last_shipping_number',
            field=models.IntegerField(default=0, max_length=6, verbose_name='Номер последней отгрузки'),
        ),
    ]
