# Generated by Django 2.2.12 on 2020-10-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goods_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.CharField(choices=[('Ожидает оценки', 'Ожидает оценки'), ('Отказ', 'Отказ'), ('Приобретен', 'Приобретен'), ('Оценен', 'Оценен')], default='Ожидает оценки', max_length=20, verbose_name='Статус'),
        ),
    ]
