# Generated by Django 2.2.12 on 2020-10-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201014_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBlockName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Блок характеристик')),
            ],
            options={
                'verbose_name_plural': 'Список названий блоков характеристик',
                'verbose_name': 'Название блока характеристик',
            },
        ),
        migrations.CreateModel(
            name='PropertyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Характеристка')),
            ],
            options={
                'verbose_name_plural': 'Список названий характеристик',
                'verbose_name': 'Название характеристик',
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PropertyName'),
        ),
        migrations.AlterField(
            model_name='propertyblock',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PropertyBlockName'),
        ),
    ]
