# Generated by Django 2.2.12 on 2020-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201026_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_id',
            field=models.CharField(max_length=6, unique=True, verbose_name='ID товара'),
        ),
    ]
