# Generated by Django 2.2.12 on 2020-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201105_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingBlank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.TextField(verbose_name='Верх документа')),
                ('bottom', models.TextField(verbose_name='Низ документа')),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.CharField(choices=[('Ожидает оценки', 'Ожидает оценки'), ('Отказ', 'Отказ'), ('Приобретен', 'Приобретен'), ('Оценен', 'Оценен'), ('Отгружен', 'Отгружен')], default='Ожидает оценки', max_length=20, verbose_name='Статус'),
        ),
    ]
